### ISSUE TITLE
Deploying ClickOnce Apps with SDK( .net core 3.1 project)

### ISSUE THREAD

**Issue by nraghu-pavan** [artiomchi/CFProxy#2]
Hi artiom chilaru,

I saw your below article on how to publish a project  SDK style (.net core 3.1) as ClickOnce deployment type , we are having the same issue. could you please help us with a sample project

https://www.flexlabs.org/2020/01/deploying-clickonce-apps-with-sdk-style-projects

your response is really apreciated

**Comment by artiomchi** [comment]
Going to close this as completely off topic :)

I've answered in the comments of the article you mentioned though.
